import { environment } from '../../environments/environment';
export const Domain =
{
    "WebsiteUrl": "",
    "GetCount": `${environment.apiUrl}/api/v1/form/count`,
    "GetTagList": `${environment.apiUrl}/api/v1/tag/all`,
    "GetPost": `${environment.apiUrl}/api/v1/post`,
    "GetPostTopic": `${environment.apiUrl}/api/v1/post/get_post_topic`,
    "GetPostCategory": `${environment.apiUrl}/api/v1/category/all`,
    "DeletePost": `${environment.apiUrl}/api/v1/post`,
    "CreatePost": `${environment.apiUrl}/api/v1/post`,
    "PatchPost": `${environment.apiUrl}/api/v1/post/update`,
    "ChangeGroupStatus": `${environment.apiUrl}/api/v1/post/group-status-modifications-in-group-post`,
    "GetSinglePost": `${environment.apiUrl}/api/v1/post/{topic}`,
    "GetLibrary": `${environment.apiUrl}/api/v1/form/library`,
    "GetLibraryTopic": `${environment.apiUrl}/api/v1/form/library/get_library_topic`,
    "GetLibraryCategory": `${environment.apiUrl}/api/v1/form/category/all`,   
    "DeleteLibrary": `${environment.apiUrl}/api/v1/form/library`,
    "CreateLibrary": `${environment.apiUrl}/api/v1/form/library`,
    "PatchLibrary": `${environment.apiUrl}/api/v1/form/library/update`,
    "ChangeGroupLibraryStatus": `${environment.apiUrl}/api/v1/form/library/group-status-modifications-in-group-library`,
    "GetSingleLibrary": `${environment.apiUrl}/api/v1/form/library/{topic}`,

    "GetEmployees": `${environment.apiUrl}/api/v1/user/employees`,
    "GroupDeletePost": `${environment.apiUrl}/api/v1/form/post`,
    "GetTeachersDelay": `${environment.apiUrl}/api/v1/form/tardy_request/search`,
    "DeleteTeachersDelay": `${environment.apiUrl}/api/v1/form/tardy_request/delete`,
    "CreateTeachersDelay": `${environment.apiUrl}/api/v1/form/tardy_request/add`,
    "PutTeacherDelay" : `${environment.apiUrl}/api/v1/form/tardy_request/update`,
    "GetSingleTeacherDelay": `${environment.apiUrl}/api/v1/form/tardy_request/search`,
    "GetClassCancellation": `${environment.apiUrl}/api/v1/form/course_cancellation/search`,
    "DeleteClassCancellation": `${environment.apiUrl}/api/v1/form/course_cancellation/delete`,
    "CreateClassCancellation": `${environment.apiUrl}/api/v1/form/course_cancellation/add`,
    "GetSingleClassCancellation": `${environment.apiUrl}/api/v1/form/course_cancellation/search`,
    "PutClassCancellation": `${environment.apiUrl}/api/v1/form/course_cancellation/update`,
    "GetTeachersDelaySingle": `${environment.apiUrl}/api/v1/form/tardy_request/search`,

    "GetEmployeeEntryExit": `${environment.apiUrl}/api/v1/form/fingerprint_scanner/search`,
    "CreateEmployeeEntryExit": `${environment.apiUrl}/api/v1/form/fingerprint_scanner/add`,
    "CreateBulkEmployeeEntryExit": `${environment.apiUrl}/api/v1/form/fingerprint_scanner/bulk_add`,
    "DeleteEmployeeEntryExit": `${environment.apiUrl}/api/v1/form/fingerprint_scanner/delete`,
    "PutEmployeeEntryExit": `${environment.apiUrl}/api/v1/form/fingerprint_scanner/update`,

    "GetLeaveRegistration": `${environment.apiUrl}/api/v1/form/leave_request/search`,
    "DeleteLeaveRegistration": `${environment.apiUrl}/api/v1/form/leave_request/delete`,
    "GetSingleLeaveRrgistration": `${environment.apiUrl}/api/v1/form/leave_request/search`,

    "GetMissionRegistration": `${environment.apiUrl}/api/v1/form/business_trip/search`,
    "DeleteMissionRegistration": `${environment.apiUrl}/api/v1/form/business_trip/delete`,
    "GetSingleMissionRegistration":`${environment.apiUrl}/api/v1/form/business_trip/search`,
    "PutMissionRegisteration":`${environment.apiUrl}/api/v1/form/business_trip/update`,
    "GetProfessorsReports": `${environment.apiUrl}/api/v1/form/`,
    "GetRemoteWorkRegistration": `${environment.apiUrl}/api/v1/form/remote_request/search`,
    "CreateRemoteWorkRegistration": `${environment.apiUrl}/api/v1/form/remote_request/add`,
    "PutRemoteWork":`${environment.apiUrl}/api/v1/form/remote_request/update`,
    "GetSingleRemoteWork": `${environment.apiUrl}/api/v1/form/remote_request/search`,
    "DeleteRemoteWorkRegistration": `${environment.apiUrl}/api/v1/form/remote_request/delete`,
    "GetSubstituteTeacher": `${environment.apiUrl}/api/v1/form/teacher_replacement/search`,
    "CreateSubstituteTeacher": `${environment.apiUrl}/api/v1/form/teacher_replacement/add`,
    "DeleteSubstituteTeacher": `${environment.apiUrl}/api/v1/form/teacher_replacement/delete`,
    "GetSingleSubstituteTeacher": `${environment.apiUrl}/api/v1/form/teacher_replacement/search`,
    "PutSubstituteTeacher":`${environment.apiUrl}/api/v1/form/teacher_replacement/update`,
    "GetSurvey": `${environment.apiUrl}/api/v1/form/survey/search`,
    "DeleteSurvey": `${environment.apiUrl}/api/v1/form/survey/delete`,
    
    "GetStudentData" :`${environment.apiUrl}/api/v1/form/student/search`,
    "DeleteStudentData" :`${environment.apiUrl}/api/v1/form/student/delete`,
    "PutStudentData" :`${environment.apiUrl}/api/v1/form/student/update`,
    "CreateStudentData" :`${environment.apiUrl}/api/v1/form/student/add`,

    "GetPaymentMethodData" :`${environment.apiUrl}/api/v1/form/payment_method/search`,
    "DeletePaymentMethodData" :`${environment.apiUrl}/api/v1/form/payment_method/delete`,
    "PutPaymentMethodData" :`${environment.apiUrl}/api/v1/form/payment_method/update`,
    "CreatePaymentMethodData" :`${environment.apiUrl}/api/v1/form/payment_method/add`,

    "GetcourseData" :`${environment.apiUrl}/api/v1/form/course/search`,
    "DeletecourseData" :`${environment.apiUrl}/api/v1/form/course/delete`,
    "PutcourseData" :`${environment.apiUrl}/api/v1/form/course/update`,
    "CreatecourseData" :`${environment.apiUrl}/api/v1/form/course/add`,

    "GetSalaryPolicyData" :`${environment.apiUrl}/api/v1/form/SalaryPolicy/search`,
    "DeleteSalaryPolicyData" :`${environment.apiUrl}/api/v1/form/SalaryPolicy/delete`,
    "PutSalaryPolicyData" :`${environment.apiUrl}/api/v1/form/SalaryPolicy/update`,
    "CreateSalaryPolicyData" :`${environment.apiUrl}/api/v1/form/SalaryPolicy/add`,

    "GetQuestionData" :`${environment.apiUrl}/api/v1/form/question/search`,
    "DeleteQuestionData" :`${environment.apiUrl}/api/v1/form/question/delete`,
    "PutQuestionData" :`${environment.apiUrl}/api/v1/form/question/update`,
    "CreateQuestionData" :`${environment.apiUrl}/api/v1/form/question/add`,

    "GetRolesData" :`${environment.apiUrl}/api/v1/form/role/search`,
    "DeleteRolesData" :`${environment.apiUrl}/api/v1/form/role/delete`,
    "PutRolesData" :`${environment.apiUrl}/api/v1/form/role/update`,
    "CreateRolesData" :`${environment.apiUrl}/api/v1/form/role/add`,

    "GetAuditEmplooyies" :`${environment.apiUrl}/api/v1/employee/search`,
    "DeleteAuditEmplooyies" :`${environment.apiUrl}/api/v1/employee/delete`,
    "PutAuditEmplooyies" :`${environment.apiUrl}/api/v1/employee/update`,
    "CreateAuditEmplooyies" :`${environment.apiUrl}/api/v1/employee/add`,

    "CreateLeaveRequest":`${environment.apiUrl}/api/v1/form/leave_request/add`,
    "PutLeaveRequest" :`${environment.apiUrl}/api/v1/form/leave_request/update`,
    "CreateMissionRegistration":`${environment.apiUrl}/api/v1/form/business_trip/add`,
    "GetAuditClass":`${environment.apiUrl}/api/v1/form/course/search`,

    

}
