import { environment } from '../../environments/environment';
export const Domain =
{
    "WebsiteUrl": "",
    "GetPost": `${environment.apiUrl}post`,
    "GetPostTopic": `${environment.apiUrl}post/get_post_topic`,
    "GetPostCategory": `${environment.apiUrl}category/all`,
    "GetTagList": `${environment.apiUrl}tag/all`,
    "DeletePost": `${environment.apiUrl}post`,
    "CreatePost": `${environment.apiUrl}post`,
    "PatchPost": `${environment.apiUrl}post/update`,
    "ChangeGroupStatus": `${environment.apiUrl}post/group-status-modifications-in-group-post`,
    "GetSinglePost": `${environment.apiUrl}post/{topic}`,
    "GetEmployees": `${environment.apiUrl}user/employees`,
    "GroupDeletePost": `${environment.apiUrl}post`,
    "GetTeachersDelay": `${environment.apiUrl}form/tardy_request/search`,
    "GetClassCancellation": `${environment.apiUrl}form/class_cancellation/search`,
    "DeleteClassCancellation": `${environment.apiUrl}form/class_cancellation/delete`,
    "CreateClassCancellation": `${environment.apiUrl}form/class_cancellation/add`,
    "GetTeachersDelaySingle": `${environment.apiUrl}form/tardy_request/search`,
    "GetEmployeeEntryExit": `${environment.apiUrl}form/fingerprint_scanner/search`,
    "GetLeaveRegistration": `${environment.apiUrl}form/leave_request/search`,
    "DeleteLeaveRegistration": `${environment.apiUrl}form/leave_request/delete`,
    "GetMissionRegistration": `${environment.apiUrl}form/business_trip/search`,
    "DeleteMissionRegistration": `${environment.apiUrl}form/business_trip/delete`,
    "GetProfessorsReports": `${environment.apiUrl}`,
    "GetRemoteWorkRegistration": `${environment.apiUrl}form/remote_request/search`,
    "CreateRemoteWorkRegistration": `${environment.apiUrl}form/remote_request/add`,
    "DeleteRemoteWorkRegistration": `${environment.apiUrl}form/remote_request/delete`,
    "GetSubstituteTeacher": `${environment.apiUrl}form/teacher_replacement/search`,
    "CreateSubstituteTeacher": `${environment.apiUrl}form/teacher_replacement/add`,
    "DeleteSubstituteTeacher": `${environment.apiUrl}form/teacher_replacement/delete`,
    "GetSurvey": `${environment.apiUrl}form/survey/search`,
    "GetAuditEmplooyies" :`${environment.apiUrl}employee/search`,
    "CreateLeaveRequest":`${environment.apiUrl}form/leave_request/add`,
    "CreateMissionRegistration":`${environment.apiUrl}form/business_trip/add`,
    "GetAuditClass":`${environment.apiUrl}form/class/search`,

    

}
